FROM jenkins/inbound-agent:latest

USER root

# עדכון apt והתקנת כלים בסיסיים
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 python3-pip git curl unzip gnupg2 lsb-release \
        docker.io \
    && rm -rf /var/lib/apt/lists/*

# התקנת Node.js עדכנית
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    node --version && npm --version

USER jenkins

