# בסיס: Jenkins inbound agent
FROM jenkins/inbound-agent:latest

# הפעלת root כדי להתקין חבילות
USER root

# התקנת Python3, pip, curl, git ו־docker
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl git docker.io && \
    rm -rf /var/lib/apt/lists/*

# חזרה למשתמש jenkins
USER jenkins

# סביבת עבודה
WORKDIR /home/jenkins/agent
